name: Release

on:
  push:
    tags:
      - 'v*'

# Minimal permissions required for creating releases
permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.22'

      - name: Set up QEMU for cross-compilation
        uses: docker/setup-qemu-action@v2

      - name: Run Goreleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}